### ISSUE TITLE
Obscure error and stdout I/O in object_factory with CRDs

### ISSUE THREAD

**Issue by thilp** [hjacobs/pykube#25]
Hello,

Thank you for maintaining this nice library.

Pykube is raising a strange error when trying to define a custom resource with no associated CRD via `pykube.object_factory` (in addition to printing some output on stdout).

I have applied some CRDs in my cluster and am trying to create resources from them with Pykube. However, there is a typo in the name of the resource I'm passing to `object_factory`, so I'm actually asking about a resource that doesn't exist.

# Expected behavior

- Pykube doesn't write anything on stdout.
- Pykube raises an exception which message explains that the resource I provided to `object_factory` does not exist (and maybe lists those that actually exist).

# Actual behavior

- Pykube writes on stdout the API server's response containing the list of existing custom resources in the cluster.
- Pykube raises a `TypeError: 'NoneType' object is not subscriptable`.

# Reproduce

```bash
$ python3 -m venv /tmp/venv
$ source /tmp/venv/bin/activate
$ python3 -m pip install pykube
```
kubectl must be linked to a running cluster.
```py
>>> import pykube as pk
>>> api = pk.HTTPClient(pk.KubeConfig.from_file())
>>> CR = pk.object_factory(api, "zalando.org/v1", "UnknownResource")
```
```
... some output from pykube's `print(resource_list)` ...
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-4-298ff14718bf> in <module>
----> 1 CR = pk.object_factory(api, "zalando.org/v1", "UnknownResource")

/tmp/venv/lib/python3.7/site-packages/pykube/objects.py in object_factory(api, api_version, kind)
    193     print(resource_list)
    194     resource = next((resource for resource in resource_list["resources"] if resource["kind"] == kind), None)
--> 195     base = NamespacedAPIObject if resource["namespaced"] else APIObject
    196     return type(kind, (base,), {
    197         "version": api_version,

TypeError: 'NoneType' object is not subscriptable
```

**Comment by hjacobs** [comment]
I agree, that's not a very helpful error handling

**Comment by hjacobs** [comment]
The debug print was already removed by someone else in https://github.com/hjacobs/pykube/pull/23
