### ISSUE TITLE
Encounter "SyntaxError: invalid syntax" when import pykube (pykube-ng: 0.28)

### ISSUE THREAD

**Issue by hakaider** [hjacobs/pykube#37]
Previously, we were using original pykube 0.15, and would like to switch to pykube-ng because original pykube no longer works with our updated kubernetes.

When we tried pykube-ng 0.28, we encounter the error below.

`import pykube
`
```
File "/opt/xyz/lib/python3.5/site-packages/pykube/__init__.py", line 9, in <module>
from .http import HTTPClient  # noqa
File "/opt/xyz/lib/python3.5/site-packages/pykube/http.py", line 167
    session.headers['User-Agent'] = f'pykube-ng/{__version__}'

SyntaxError: invalid syntax
```

**Comment by hakaider** [comment]
Looks like it is because of f-strings in Python 3.6,  we are using Python 3.5.2

Hi @hjacobs , Is it possible to make PyKube-ng compatible with Python 3.5 ?

**Comment by hjacobs** [comment]
I don't really want to support old Python versions (I rather make sure Python 3.8 works). We live in a world of containers, so there should be no issues in using a more recent Python version inside e.g. a Docker container. Even Ubuntu 18.04 LTS has Python 3.6 as default (and also ships 3.7).

I updated the README to mention 3.6+.
